image: node:lts
variables:
  FF_USE_FASTZIP: 'true'

cache:
  untracked: true
  policy: push
  key: ${CI_COMMIT_SHORT_SHA}
  paths:
    - node_modules/

stages:
  - setup
  - build
  - test
install:
  stage: setup
  script:
    - echo "Installing dependencies"
    - npm ci

build:
  stage: build
  cache:
    untracked: true
    key: ${CI_COMMIT_SHORT_SHA}
    policy: pull
  script:
    - echo "Building application"
    - npm run build

lint:
  stage: test
  cache:
    untracked: true
    key: ${CI_COMMIT_SHORT_SHA}
    policy: pull
  script:
    - echo "Checking format code eslint"
    - npm run lint
    - echo "Checking types"
    - npm run ts
# test:
#   stage: test
#   cache:
#    untracked: true
#    key: ${CI_COMMIT_SHORT_SHA}
#    policy: pull
#   before_script:
#     - apt-get update
#     - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#     - apt install -y ./google-chrome*.deb;
#     - export CHROME_BIN=/usr/bin/google-chrome
#   script:
#     - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
