language: node_js

node_js:
  - 16

install:
  - npm install
  - npm install -g @angular/cli

script:
  - ng build -c pre-production
  - cd dist/zelli
  - zip -r "${TRAVIS_BUILD_DIR}/zelli_${TRAVIS_TAG}.zip" * 
  
deploy:
  provider: releases
  api_key:
    secure: iNWgUFmNMnCsWtq6wbaeiPjGholeXxIFsNsyXOuokphI+hk2Z55nkuMLQwO2kATnMYF+6bhnXZ1MNY5tEQ8thgA5PWK1xcY63lfgpu22ySGzgqeXKFw8wz6mkTPpzx+tRm9s/8lqEcRz7Bm6kLsAfJ9i58f/y/S06czqdiDarOG49NUCQJP0lbOxNgHiMONtPZHbXffze/J/1iQ5QsedI3QWVskKlwO/EwL0TTj9LZg0qucoQZ5/H1yai4dINUQDJIY9/2Iu9PlhMERHEiwBlTPJjnMHwUybGu98HbpYqSbXSQx2jfmTGrzbnVxLIfmIQ2Pxvyx5vS6xr+nyoW19ltxzsE5s6DH7y5G9pYAzRFE2MC4PnbC5EwuYMRo+u8NxCMzSL1iLc0R/tHSKMt3ehp9F1sLuMfyi6cB7sFEUN6AjfDmcPINw0kMJmdV7D9UC+b+0/mx3WmcT/LMRA67t8+ViONAH0ZyRZoU+G1OyJkSnSO0iWJVTzpy0OEkvUZD8FjvLu00wZDobT6E20WjAPiEKA7f5AYRZTTzIdQDGxaNjbW7w14HOBteejXqGo1eqzeUIa9OWit8IXc4JqfvhhQctSsTwOizjtmHNOF3EsQhKaB79ofGeCMpYxAt75Ad3MPFaZDsF7qR1qFSQci7Tc5itF8cBI3fz/M4sjh9qdsI=
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/*.zip"
  skip_cleanup: true
  on:
    tags: true
