language: node_js

node_js:
  - 16

install:
  - npm install
  - npm install -g @angular/cli

script:
  - ng build -c pre-production
  - cd dist/zelli
  - zip -r "${TRAVIS_BUILD_DIR}/zelli_${TRAVIS_TAG}.zip" * 
  
deploy:
  provider: releases
  api_key:
    secure: XyDmh18mbbKUjC5DSGjTyv6V5zrGDrMnyqLb3vcqCYCs8hvHUg1SnCaKLGMY/90C3VplgIiMAHTNOjdcB87Jhd9RvhmX2dBYiwu2oWgqkHUy6nB6PQTJiNISXTT0+zX2mQW91RQHAVCugAlSDgbxBWszQJW7o9BzsqEPzr6w6XRr52YxB4Y6hordxDnhOXWwLkp83+BF+0xy/oY2SnTULcp8OaSOR7MDsdpXOkzb0I1OEpnb+9ldBacX9Ryhr/d9MjCLoDLmbnBQs04kPGkIUqgp0PPlQtBUK/wWNiMFvIaioDjQEwDNs6gNEo2zReC0R5gRcLTAVSz1JMsqPZEAYIz+6FFp6YBiPmmQFoHgH/vwoJnyHhjMFUXTOOVQeLlQM65hywMumWeSD34gB264v9S9QtIFPGIyLIwhUYgL3bmzqOPFWN2WWkGrV/p0iel1KriereErfRgY/v9dC4Qa+1NwpvsZo5P6whaoQrfB+UxjTsZL29+yQP7xzouXpMdIf0os3V8eMem+diqmD7Mp9XDXGTmq/DzK4aCWroYQ7q1goVD0iM5cAeP8GwJXcFqakE11LCCetKWgAsjp8V76exISUQOmncDBoMsPh3DbQC4rznziZWlRvrnPlCa7r21K8I4Vl7AaPVPMDmF2C/LXcyxzU/OikK2gyPLS7hYJWBk=
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/*.zip"
  skip_cleanup: true
  on:
    tags: true
