language: node_js

node_js:
  - 16

install:
  - npm install
  - npm install -g @angular/cli

stages:
  - analyse-code
  - build-release-preprod
  - build-release-recette
  - build-release-prod
  
jobs:
  include:
  - stage: analyse-code
    script:
    - npm run lint
  - stage: build-release-preprod
    script: 
    - ng build -c pre-production
    - cd dist/zelli
    - zip -r "${TRAVIS_BUILD_DIR}/zelli_${TRAVIS_TAG}-preprod.zip" * 
    deploy:
      provider: releases
      api_key:
        secure: qvj+7KbBW6bheJKlpbXtEZHy66MSzD/s9KLuEgktKJOo/w32HaJt1NEjDzIN7awiL9QYofEIm5umDfxdWGmSmyTb24D3Ijj3yGALlJvi5nD44W/zxyW2ME9n4he6o2Tj0A7Zj8Eg78purUkLuar1Gth5Y1iwX64UmKbyMjps1KaVvv95gD9qgOhdGKv0jL+D+BJFe3wqGUAhKqbLAD57jHhIlrsyJs5AGdXCP5Y4tWjwrgDmOyqOdaR7BaCrJwlw/MVRSJ8eAfvyzkdAbccYlWSrQN5eNUz/YorhhVJzDnxQl4VISsbY0xX6uRMwNRrec2+FEmVQphulhahEECGdKQNcl9YnQVMr7EhKWlfBQgiVMCab1IfWi+PujQvMs6NZ1aTVC/cLv6Gw8g9Wf3mMA4LFYXH2N/m1ASfcafvI4xVyNtW+JhEBMi603uIXZlp8ft0veNdz5SjvycjKNoQkyP8Le9pFFI6l02Fwb8X9upNSIYkODjCrWLuUIkDW7RNEOyb/CLf6oq5OyEEHU5j4EfFJ+FjWF31bnaPk1rj1PpylizzCMEpUsKPwy9G1md5N5iYrxSZBppMfixYRcxM4tdD5lPV6W5L6pHq64s/7nRbbVXUu/xVftHK1MAj9mnDfS7WHJKkL0dqi9GVLOKP99p3vKyZfENOAJBOOVOJFac0=
      file_glob: true
      file: "${TRAVIS_BUILD_DIR}/*.zip"
      skip_cleanup: true
      on:
        tags: true
  - stage: build-release-recette
    script: 
    - ng build -c R7
    - cd dist/zelli
    - zip -r "${TRAVIS_BUILD_DIR}/zelli_${TRAVIS_TAG}-recette.zip" * 
    deploy:
      provider: releases
      api_key:
        secure: qvj+7KbBW6bheJKlpbXtEZHy66MSzD/s9KLuEgktKJOo/w32HaJt1NEjDzIN7awiL9QYofEIm5umDfxdWGmSmyTb24D3Ijj3yGALlJvi5nD44W/zxyW2ME9n4he6o2Tj0A7Zj8Eg78purUkLuar1Gth5Y1iwX64UmKbyMjps1KaVvv95gD9qgOhdGKv0jL+D+BJFe3wqGUAhKqbLAD57jHhIlrsyJs5AGdXCP5Y4tWjwrgDmOyqOdaR7BaCrJwlw/MVRSJ8eAfvyzkdAbccYlWSrQN5eNUz/YorhhVJzDnxQl4VISsbY0xX6uRMwNRrec2+FEmVQphulhahEECGdKQNcl9YnQVMr7EhKWlfBQgiVMCab1IfWi+PujQvMs6NZ1aTVC/cLv6Gw8g9Wf3mMA4LFYXH2N/m1ASfcafvI4xVyNtW+JhEBMi603uIXZlp8ft0veNdz5SjvycjKNoQkyP8Le9pFFI6l02Fwb8X9upNSIYkODjCrWLuUIkDW7RNEOyb/CLf6oq5OyEEHU5j4EfFJ+FjWF31bnaPk1rj1PpylizzCMEpUsKPwy9G1md5N5iYrxSZBppMfixYRcxM4tdD5lPV6W5L6pHq64s/7nRbbVXUu/xVftHK1MAj9mnDfS7WHJKkL0dqi9GVLOKP99p3vKyZfENOAJBOOVOJFac0=
      file_glob: true
      file: "${TRAVIS_BUILD_DIR}/*.zip"
      skip_cleanup: true
      on:
        tags: true
  - stage: build-release-prod
    script: 
    - ng build -c production
    - cd dist/zelli
    - zip -r "${TRAVIS_BUILD_DIR}/zelli_${TRAVIS_TAG}.zip" * 
    deploy:
      provider: releases
      api_key:
        secure: qvj+7KbBW6bheJKlpbXtEZHy66MSzD/s9KLuEgktKJOo/w32HaJt1NEjDzIN7awiL9QYofEIm5umDfxdWGmSmyTb24D3Ijj3yGALlJvi5nD44W/zxyW2ME9n4he6o2Tj0A7Zj8Eg78purUkLuar1Gth5Y1iwX64UmKbyMjps1KaVvv95gD9qgOhdGKv0jL+D+BJFe3wqGUAhKqbLAD57jHhIlrsyJs5AGdXCP5Y4tWjwrgDmOyqOdaR7BaCrJwlw/MVRSJ8eAfvyzkdAbccYlWSrQN5eNUz/YorhhVJzDnxQl4VISsbY0xX6uRMwNRrec2+FEmVQphulhahEECGdKQNcl9YnQVMr7EhKWlfBQgiVMCab1IfWi+PujQvMs6NZ1aTVC/cLv6Gw8g9Wf3mMA4LFYXH2N/m1ASfcafvI4xVyNtW+JhEBMi603uIXZlp8ft0veNdz5SjvycjKNoQkyP8Le9pFFI6l02Fwb8X9upNSIYkODjCrWLuUIkDW7RNEOyb/CLf6oq5OyEEHU5j4EfFJ+FjWF31bnaPk1rj1PpylizzCMEpUsKPwy9G1md5N5iYrxSZBppMfixYRcxM4tdD5lPV6W5L6pHq64s/7nRbbVXUu/xVftHK1MAj9mnDfS7WHJKkL0dqi9GVLOKP99p3vKyZfENOAJBOOVOJFac0=
      file_glob: true
      file: "${TRAVIS_BUILD_DIR}/*.zip"
      skip_cleanup: true
      on:
        tags: true
       
