language: node_js

node_js:
  - 16

install:
  - npm install
  - npm install -g @angular/cli

script:
  - ng build -c pre-production
  - cd dist/zelli
  - zip -r "${TRAVIS_BUILD_DIR}/zelli_${TRAVIS_TAG}.zip" * 
  
deploy:
  provider: releases
  api_key:
    secure: gyN/b7wGA8+/PaMTLljdqEycN63Tz3CB1tovS/yjIe9GtalVo67lfVieFJpNBtRuOnzxLyYr+fubZvExlffHfrTEu4a+x3cuaOQftquNi51XD0fFrgYdKEcB7qAKjTRbAkBiXLvjZc3wxqxFwxVKYU3oTrnZIz7+/hgicJFXv1+urOeXbMVtpHMHrYpDyTW7Tp1UZvMWNYexOUOYJrnJXcBMzte1GiLDF9HlJVB0Yy38M6SjLzeqOEZwFCoaEHuSTVxRyNqKX6gvObd4pUhWbaAp+epccEiqshehaBf/xSRWs/InDijYU1NEs/pT5BcWfEVnTrwNeLOFJ5JnjZRwSK/Dwge1U+d2Pi3SWotUEktZpcLB/j7+lsTRWk1I1+duxcMf8ON4ygIAJQHTHHFR/q2G1KxIH3dKxUuXQjukgq6Osf5m0I9/fYef/C7z+zzaWgvwF6BllXDO+fXqVQSCUF/otVUoTt/B0pqP9SWY7YjSQm4cYJ/6ThzQN63CDkjaeKg/c6vTxXaaH4z3IvAnELOXnI7mv3kxhGblkU8WwUGx41IVTtz/1hdhexKnAlBUOakXsP1hFzJy22/d496Q8H3eYCdn4wWD5Om2tg6pcaSfP0Yqp0osHrmqK/63Z24w7CcrKkTLhbEA5pK5E/VOwxENuZWwPdb3FNp8v/fJP0U=
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/*.zip"
  skip_cleanup: true
  on:
    tags: true
