language: node_js

node_js:
  - 16

install:
  - npm install
  - npm install -g @angular/cli

script:
  - ng build -c pre-production
  - cd dist/zelli
  - zip -r "${TRAVIS_BUILD_DIR}/zelli_${TRAVIS_TAG}.zip" * 
  
deploy:
  provider: releases
  api_key:
    secure: G6Ycjr/6hAmRhBlAOqBDYqFJx9t9Y/SjKs2FFiHd329ohqO+/GffpmL2BwW6GXpriI/TnUjow9DDpjBzNTjf5AOZpisx3PQegH8kExt2/VwhtBMJYVZhcN6G7EOwMh72wknp+sOe7LC7dnnt/g2EAcIuBtDilmeUMRj6yvhT63qGHwZN6omDcwNjf7Dtd6sC3u10abqAJvhRqQ+vFpmyyhE/w/Pas6wUmJR+Q3DgDWfLt2ThozaXUJFxVIQF+JUrC/aNphzQh4f3Ak7FpVlkvJjl5fh2g+6IWh+HNfYC9/s4A4ORsSoBKR3kHR7rMjQmrHlhUUNiD9qiJv2cGyUptldG4Cf1QwRq9iRgKDXcRDxJdrHcpWUvxk8jvkXXxCkaSQOqD/zx52xbQ7DfZLhV8CFub9TiLI4W/qYPeGOEOcWLJOvW7jYKq1CNeYRjlMZzekirbIplUVsL4HtVnUG0Ru31PoF9Pxg55h+fIbrtRUgQtKR6QAOTTgF3WiFCf2e4OikuktdGCLyWbS7MsH4Zftj8UIy/GtM+jRvX42t3/kVpXiSD2xWdSeMFTeo4XPZ3Ei0v8dWL9Go2dvD+eg4LqJgKP2xZYgeZjDcG61ltGGpXhuGSyinWYGPvs4uqIYzEaBZ5UWBDDcWPwaon6/OEvDPq3QhZRpco/DlHq7tZuzc=
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/*.zip"
  skip_cleanup: true
  on:
    tags: true
