export type Contact = {
  id: string;
  title: string;
  firstname: string;
  lastname: string;
  gender: string;
  idPicture: string;
  job: string;
  location: Partial<Location>;
  phoneNumber: string[];
  email: string;
};

export type Location = {
  id: string;
  title: string;
  stairOrCorridor: string;
  enterNumber: string;
  roadNumber: string;
  roadName: string;
  place: string;
  postalCode: string;
  city: string;
  website: string[];
  cs: string;
  cedex: string;
};

export type LocationFromApi = {
  id: string;
  title: string;
  etageCouloirEscalier: string;
  entreeBatimentImmeuble: string;
  ndeVoie: string;
  libelleDeVoie: string;
  lieudit: string;
  codePostal: string;
  commune: { id: string; title: string };
  libelleAutreAdresse: string;
  etageCouloirEscalier2: string;
  entreeBatimentImmeuble2: string;
  ndeVoie2: string;
  libelleDeVoie2: string;
  lieudit2: string;
  codePostal2: string;
  cs2: string;
  cedex2: string;
  telephone: string[];
  email: string[];
  siteInternet: string[];
  plusDeDetailInterneDBID: string;
  plusDeDetailExterne: string;
  texteAlternatifLien: string;
  complementTypeDacces: string;
  pourQui: string;
  modalitesDaccueil: string;
  horairesEtAcces: string;
  transportsEnCommun: string;
  parkings: string;
  description: string;
  lienDeLaPageFacebook: string;
  lienDeLaPageInstagram: string;
  toutesLesCommunesDuDepartement: false;
  arretsDeTransportsEnCommunAccess: false;
  presenceDunePlacePMRSurLespacePu: false;
  presenceDunePlacePMRDansLERP: false;
  visiophone: false;
  sonnette: false;
  signaletiqueDirectionnelle: false;
  entreeDePlainpied: false;
  portesAutomatiques: false;
  rampeFixe: false;
  rampeAmovible: false;
  ascenseurMontecharge: false;
  presenceDePersonnelALaccueil: false;
  personnelDaccueilFormeAuxDiffere: false;
  personnelDaccueilFormeALaLangueD: false;
  siOuiHorairesDePresence: string;
  planningDeMiseEnAccessibiliteDuS: string;
  informationsComplementaires: string;
  externalLinkSet: string[];
};

export type ContactFromApi = {
  id: string;
  title: string;
  nom: string;
  prenom: string;
  civilite: string;
  photoDidentite: string;
  fonction: string;
  lieuDeRattachement: Partial<LocationFromApi>;
  telephone: string[];
  adresseMail: string;
};
